---
title: "Task 6"
author: "Haleigh Borich"
date: "9/21/2021"
output:
    html_document:
      theme: united
      keep_md: True
      code_folding: hide
---
Load Library
```{r}
library(tidyverse)
library(ggrepel)
library(lubridate)
```
Create Data
```{r}
iris
head(iris)
tail(iris)
view(iris)
str(iris)
```
Create a Dataset with only Petal Width
```{r}
WidthData <- iris %>%
  group_by(Species) %>%
  filter(row_number(desc(Petal.Width)) == 1)
WidthData

```
Create a Dataset with only Petal Length
```{r}
LengthData <- iris %>%
  group_by(Species) %>%
  filter(row_number(desc(Petal.Length)) == 1)
```
Create a Vizualisation
```{r}
irisplot1 <- ggplot(data = iris, mapping = aes(x = Sepal.Length,
                                               y = Sepal.Width)) +
  geom_point(mapping = aes(color = Species, shape = Species))+
  geom_point(size = 3, shape = 1, color = "black", data = WidthData) +
  geom_text(aes(color = Species, label = "Largest Petal Width"), data = WidthData, nudge_y = .01) +
  geom_point(size = 3, shape = 1, color = "black", data = LengthData) +
  geom_text(aes(color = Species, label = "Largest Petal Length"), data = LengthData, nudge_y = -.01) +
  scale_x_log10() + scale_y_log10() +
  labs(x = "Sepal Length (cm)",
       y = "sepal Width (cm)",
       title = "Different Iris Species Have Different Sepal Sizes",
       subtitle = "The Largest Petal Sizes For Each Species Do Not Correspond To The Largest Sizes") +
  theme(legend.position = "bottom")

irisplot1
```
Import New Data
```{r}
ScrabbleData <- read_csv("scrabble_games.csv")
```
Look at Data
```{r}
head(ScrabbleData)
tail(ScrabbleData)
str(ScrabbleData)
```
Filter Data
```{r}
ScrabbleAll <- ScrabbleData %>%
  select(date, winnerscore, loserscore) %>%
  pivot_longer(c("winnerscore", "loserscore"), names_to = "win-loss",
               values_to = "score") %>%
  filter(score > 0) %>%
  mutate(year = year(date),
         week = week(date))
head(ScrabbleAll)
```
Find Weekly Averages
```{r}
weeklyscore1 <- ScrabbleAll %>%
  group_by(year, week) %>%
  summarize(avgscore = mean(score), Date = min(date))

head(weeklyscore1)
str(weeklyscore1)
```
Seperate into Two Datasets
```{r}
before <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date > as.Date("2006-03-01")) %>%
  summarize(avgscore = mean(score), Date = min(date))
head(before)

after <- ScrabbleAll %>%
  group_by(year, week) %>%
  filter(date < as.Date("2006-03-01")) %>%
  summarize(avgscore = mean(score), Date = min(date))
head(after)
```
Create Vizualisation
```{r}
scrabblegraph <- ggplot(data = weeklyscore1, mapping = aes(x = Date, y = avgscore)) +
  geom_point() +
  geom_smooth(data = before, method = lm, color = "blue") +
  geom_point() +
  geom_smooth(data = after, method = lm, color = "orange") +
  geom_vline(xintercept = as.Date("2006-03-01") , linetype = "dotted") +
  coord_cartesian(ylim = c(355,405), expand = FALSE) +
  scale_x_date(date_breaks = "3 months",
               limits = as.Date(c('1/6/2005', '1/9/2006'), format = "%d/%m/%Y"),
               date_labels = "%b-%Y") +
  annotate("text", x = as.Date("2005-12-05"), y = 380, label = "Trend Before", color = "orange", size = 3) +
  annotate("text", x = as.Date("2006-07-05"), y = 380, label = "Trend After", color = "blue", size = 3) +
  annotate("text", x = as.Date("2006-03-01"), y = 390, label = "Dictionary Updated", color = "black", size = 3) +
  labs(x = " ",
       y = "Average Score",
       title = "Scrabble score in the age of 'QI' and 'ZA'",
       subtitle = "Weekly average scores before and after the addition of around 11,000 words
to the Scrabble dictionary",
       caption = "Source: FiveThirtyEight") +
  theme_bw()
scrabblegraph

```

