---
title: "Task4"
author: "Haleigh Borich"
date: "9/8/2021"
output: html_document
        keep_md: True
        theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load Packages In
library(dplyr)
library(tidyverse)
```

```{r}
# Create Name of Data Set
iris_data <- iris
```

```{r}
# Look at Structure and Find a quick view
head(iris_data) # Shows first 6 lines
tail(iris_data) # Shows last 6 lines
str(iris_data) # Looks at the Structure of the Data Frame
```

```{r}
# Arrange the Iris Data by Sepal.Length and display the first 10 rows
SepalArr <- arrange(iris_data, Sepal.Length)
head(SepalArr, n = 10)
```

```{r}
# Putting Species and Petal.Width columns into a new data set
testdat <- select(iris_data, Species, Petal.Width)
head(testdat)
```

```{r}
# New Table that has the mean for each variable in Species
species_mean <- iris_data %>%
  group_by(Species) %>%
  summarise(
    SepalWidthMean = mean(Sepal.Width), SpealLengthMean = mean(Sepal.Length),
    PetalWidthMean = mean(Petal.Width), PetalLengthMean = mean(Petal.Length))
species_mean
```

```{r}
# New Data Frame with observations from at least 3 Sepal.Width and not 2.5 for Petal.Width
iris_min <- filter(iris_data, Sepal.Width <= 3, Petal.Width != 2.5)
head(iris_min)
```

```{r}
# Data Frame with Sepal.Size information
iris_size <- iris_data %>%
  mutate(Sepal.Size =
           case_when(
             Sepal.Length < 5 ~ "small",
             Sepal.Length >= 5 & Sepal.Length < 6.5 ~ "medium",
             Sepal.Length >= 6.5 ~ "large"))

iris_size
```

```{r}
# Ranking of all the data by Petal.Length where a ranking of 1 us the largest Petal.Length, ordered by ranking
iris_rank <- arrange(iris_data, desc(Petal.Length))
iris_rank  
```

```{r}
# New Table with the means and standard deviation for each speacies
?summarise_all()

MeanForAll <- iris_data %>% group_by(Species) %>% summarize_all(list(Mean = mean, Std_Dev = sd))

MeanForAll
```

```{r}
# Novel Questions

##  1. What is Sleep Debt?
### Kaylie Kappelemen - Not getting enough sleep one day and trying to make up for it the next day
### Carolyn Schneck - Sleep Deprivation 
### Steve Radley - Over time the sleep you miss adds up 
### Max Wheeler - Getting below the reccomended hour of sleep
### Dimas - Missing out on sleep 
## From this, we can see that most college students have a basic knowledge of what Sleep Debt is. However the definition of Sleep Debt is the difference between the amount of sleep someone needs and the amount they actually get. 

## 2. What is the most popular streaming site?
### Kaylie Kapplemen - Netlix
### Carolyn Schneck - YouTube
### Steve Radley - YouTube
### Max Wheeler - YouTube
### Dimas - HBO Max
## The top streaming site is currently Netlifx with 209 Million active users. Most college students tend to use YouTube as a way to stream but it is not an actual paid streaming site. 

## 3. Does working out make you more productive 
### Kaylie Kapplemen - Yes 
### Carolyn Schneck - Yes, because it releases endorphins and helps with motivation
### Steve Radley - Yes
### Max Wheeler - Yes
### Dimas - Yes
## It is proven that exercise does make you feel better since it improves mood. Working out is hard to begin, but once the endorphins start moving it increases productivity. 
```



