---
title: "Task21"
author: "Haleigh Borich"
date: "11/17/2021"
output: html_document
---

```{r}
library(tidyverse)
library(maps)
library(USAboundaries)
library(leaflet)
```

```{r}
chet <- sf::st_as_sf(maps::map("state", plot = FALSE, fill = TRUE))

idaho <- us_counties(states = "ID")

cities <- us_cities()

states <- us_cities()
```

```{r}
top_three <- states %>%
  filter(state_name != "Alaska", 
         state_name != "Hawaii") %>%
  group_by(state_name) %>%
  arrange(desc(population)) %>%
  slice(1:3)
```

```{r}
top_one <- top_three %>%
  slice(1:1)

num_two <- top_three %>%
  slice(2:2)

num_three <- top_three %>%
  slice(3:3)
```

```{r}
top_city <- top_one %>%
  mutate(coords = geometry) %>%
  separate(coords, into = c("long", "lat"), sep = ",") %>%
  separate(long, into = c("out", "Long"), sep = 2) %>%
  separate(lat, into = c("Lat", "out"), sep = -1) %>%
  mutate(Lat = as.numeric(Lat), Long = as.numeric(Long))

```

```{r}
leaflet() %>%
  addTiles() %>%
  addPolygons(data = chet, fillColor = "white", weight = 1, opacity = 1, color = "grey", fillOpacity = 0.5) %>%
  addPolygons(data = idaho, fillColor = "white", weight = 1, opacity = 1, color = "grey", fillOpacity = 0.5) %>%
  addCircleMarkers(data = top_one, radius = 4, color = "#083292", stroke = FALSE, fillOpacity = 0.9) %>%
  addCircleMarkers(data = num_two, radius = 4, color = "#376FF0", stroke = FALSE, fillOpacity = 0.9) %>%
  addCircleMarkers(data = num_three, radius = 4, color = "#9FB5E8", stroke = FALSE, fillOpacity = 0.9) %>%
  addMarkers(data = top_city, lat = ~Lat, lng = ~Long, popup = ~as.character(population), label = ~city)
```

